# Generated by Django 6.0.3 on 2026-03-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_accountcredit_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='registration_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
